moltar/typescript-runtime-type-benchmarks

README.md, cases/index.ts, cases/zod.ts, package-lock.json, package.json, test/__snapshots__/abstract.test.ts.snap
=> feat: adds zod

README.md, cases/index.ts, cases/rulr.ts, package-lock.json, package.json, test/__snapshots__/abstract.test.ts.snap
Closes #337 
Hey @moltar, tried to keep this as close to #105 as possible so I left out the generation of the results files from running `npm start`. Let me know if you need me to add those.
Rulr's performance was pretty surprising, I think the issue is that Rulr will find all of the errors in the object before throwing an error, I might implement a `bail` option for the object rule and see if that improves the performance.
=> feat: adds rulr

README.md, cases/index.ts, cases/simple-runtypes.ts, package-lock.json, package.json, test/__snapshots__/abstract.test.ts.snap
=> feat: adds simple-runtypes

index.ts
=> fix: handle TypeScript 4.1 breaking change

README.md, cases/index.ts, cases/valita.ts, package-lock.json, package.json, test/__snapshots__/abstract.test.ts.snap
Hello! Thank you for this repo, it's a great resource for finding out about what kinds of libraries and approaches there are 🙂
This pull request adds our fledgling project [valita](https://github.com/badrap/valita) to the benchmark - if it's ok for you.
=> feat: adds valita

cases/index.ts
=> fix: enables rulr

cases/index.ts, package-lock.json, package.json
=> fix: Fixes Rulr for #847

docs/dist/app.js
Docs need to be built locally and checked into the repo - forgot that in the last PR.
=> docs build

README.md, cases/index.ts, cases/r-assign.ts, package-lock.json, package.json, test/benchmarks.test.ts
This PR adds the r-assign package to the benchmark list. Fixes #797
=> Add r-assign

README.md, cases/index.ts, cases/sinclair-typebox.ts, package-lock.json, package.json, test/benchmarks.test.ts
=> add @sinclair/typebox

README.md, cases/index.ts, cases/vality.ts, package-lock.json, package.json, test/benchmarks.test.ts
=> feat: adds `vality`

.github/workflows/pr.yml, .github/workflows/release.yml, benchmarks/helpers/main.ts, docs/app.tsx, docs/dist/app.js
=> feat: add node v19

README.md, cases/index.ts, cases/succulent.ts, package-lock.json, package.json, test/benchmarks.test.ts
Hello!
Just wanted to add another contender to the ranking :)
=> feat: adds `succulent@0.18`

.github/workflows/pr.yml, .github/workflows/release.yml, README.md, benchmarks/helpers/main.ts, docs/app.tsx, docs/dist/app.js
Remove node 14 as it will be EOL in 5 days.
Fixes #1062
=> feat: add node 20

docs/app.tsx, docs/dist/app.js
=> Show ops as labels

cases/valibot.ts
https://github.com/moltar/typescript-runtime-type-benchmarks/pull/1129
=> fix: update loose and strict assert of Valibot

README.md, cases/arktype.ts, cases/index.ts, package-lock.json, package.json, test/benchmarks.test.ts
https://github.com/arktypeio/arktype
fixes: #1045
=> add arktype

README.md, cases/index.ts, cases/unknownutil.ts, package-lock.json, package.json, test/benchmarks.test.ts
Sorry I mistakely closed my old PR #1161 
New and the same one
https://github.com/lambdalisue/deno-unknownutil
=> add unknownutil

README.md, cases/index.ts, cases/rescript-schema.ts, package-lock.json, package.json, test/benchmarks.test.ts
https://github.com/DZakh/rescript-schema/releases/tag/v6.0.0
=> Rename rescript-struct to rescript-schema

README.md, cases/index.ts, cases/mondrian-framework.ts, package-lock.json, package.json, test/benchmarks.test.ts
Add benchmarks for https://mondrianframework.com/docs/docs/foundamentals/model/definition
=> feat: add `@mondrian-framework/model`

.github/workflows/pr.yml, .github/workflows/release.yml, docs/app.tsx, docs/dist/app.js
- Added Node.js 21 and 22
- Updated actions in workflows
=> Updated Node.js versions and workflows

docs/app.tsx, docs/dist/app.js, docs/index.html
Added buttons to star/fork
They can be customized https://buttons.github.io/
What do you think about this @moltar @hoeck ?
=> Added buttons for 'Star' and 'Fork'

README.md, cases/caketype.ts, cases/index.ts, package-lock.json, package.json, test/benchmarks.test.ts
https://github.com/justinyaodu/caketype
Closes 
https://github.com/moltar/typescript-runtime-type-benchmarks/pull/1029
https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1028
=> Add caketype

tsconfig.json
As currently the lowest version we support is node 16 and based on https://node.green/ we can safely increase target version to `ES2021`
=> Updated TypeScript configuration

README.md
Closes https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1012
=> Added detailed test cases to README

.github/workflows/pr.yml, .github/workflows/release.yml, bun.lock, package.json, start.sh
Update bun version and add specific bun start script. 
More context: https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1551
Closes: https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1551
=> chore: update bun version and add bun start script

.github/workflows/release.yml
Trying to fix release action https://github.com/moltar/typescript-runtime-type-benchmarks/actions/runs/12817950376
=> chore: update release workflow for git operations

bunfig.toml
https://bun.sh/docs/runtime/bunfig#run-bun-auto-alias-node-to-bun
Closes: https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1551
=> chore: add run configuration for bun

README.md, bun.lock, cases/index.ts, cases/stnl.ts, package-lock.json, package.json, test/benchmarks.test.ts
Fix messy commit history and apply all changes suggested from previous PR.
=> Add stnl validator

docs/dist/app.js
i didn't know i had to update dist/app.js when opening #1613. 
maybe we could switch to action-based docs deploying  like in https://github.com/actions/configure-pages to simplify stuff?
`npm run docs:serve`
=> build: update dist/app.js for deno

README.md, cases/cleaners.ts, cases/index.ts, package-lock.json, package.json, test/benchmarks.test.ts
This adds the cleaners library to the test suite.
=> Add cleaners case

README.md, cases/index.ts, cases/joi.ts, download-packages-popularity.ts, package-lock.json, package.json, test/benchmarks.test.ts
Joi benchmarks
Run tests
https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1693
=> feat: integrate Joi benchmarks

cases/jet-validators.ts, package-lock.json, package.json
Provide a brief summary of the changes made, including any issues resolved. Include the purpose and context behind these updates.
Explain how the changes can be tested.
=> Update jet-validators to the latest version (small performance improvement)

README.md, cases/index.ts, cases/sury.ts, download-packages-popularity.ts, package-lock.json, package.json, test/benchmarks.test.ts
Added a successor of the ReScript Schema - https://github.com/DZakh/sury
=> Add Sury to the benchmark
