moltar/typescript-runtime-type-benchmarks

README.md, cases/marshal.ts, package-lock.json, package.json, test/__snapshots__/abstract.test.ts.snap
Also made sure it only validates using the `validate`
method. Although the new Marshal version is even with `validatedPlainToClass` the fastest by a huge margin, it wouldn't be fair to compare against other validators that do only validation and not class instance creation.
=> Used newest Marshal version with JIT validation.

README.md
Hey @moltar this is just to add a warning in the readme until #497 occurs since people have been getting the wrong idea about the performance of different libraries with the current apples-to-oranges comparisons across functionality.
=> add note about incorrect comparisons to readme

graph.ts
Follows our discussion on https://github.com/moltar/typescript-runtime-type-benchmarks/pull/547
=> fix: Resolves breaking change in svgo

package-lock.json, package.json, test/__snapshots__/abstract.test.ts.snap
This pull request updates @badrap/valita to v0.0.24 and updates the related test snapshot.
Valita's v0.0.24 changed its error output format for missing object keys, so the snapshot checks in tests were failing.
=> Update to @badrap/valita v0.0.24 and rebuild snapshot

README.md, cases/ajv.ts, cases/index.ts, package-lock.json, package.json
Adds AJV to test cases, I saw the open ticket #683 and agree that AJV is a very popular package that is used in a lot of places. 
AJV now has something called AJV standalone mode. 
>Ajv supports generating standalone validation functions from the JSON Schema into functions at compile/build
time. These functions can then just be consumed during runtime to do validation checks against JSON.
You can read more about it here https://ajv.js.org/standalone.html and you can also see some more examples and documentation in this PR I made https://github.com/ajv-validator/ajv/pull/1866. What I am getting at is that you can use other packages to map TS native types to JSON Schema, then from that create validation functions for your types at compile time which are consumed at runtime. Throw this in a …
=> feat: add ajv

docs/app.tsx
While debugging I've randomly noticed that missingBenchmarks always contain all benchmarks even if they are not missing. Although they are filtered out later, I still decided to do this small fix.
=> fix: missing benchmarks filter

benchmarks/helpers/main.ts
Before if there were a disabled case it couldn't load it:
After the fix `superstruct` benchmark and some other started working again:
=> Fix benchmarks with disabled cases

cases/index.ts, cases/to-typed.ts, package-lock.json, package.json, test/benchmarks.test.ts
Added [to-typed](https://github.com/jsoldi/to-typed). See issue https://github.com/moltar/typescript-runtime-type-benchmarks/issues/897
=> feat: add to-typed

.github/workflows/release.yml, benchmarks/helpers/main.ts
A comment in release.yml now lists all node-version references that need to be synced.
I'm not using ENV vars because that would only help with the preview image generation. pr.yml and and app.tsx would need sth. more complicated and I think manually tracking them in a few files is still easier.
=> use node v18 for the preview image

index.ts
=> fix: escape internal command arguments

benchmarks/helpers/graph.ts, benchmarks/helpers/main.ts
* sort by operations (fastest first)
* add more info to the title
* remove old dead test code
old: 
new:
@mmamedel  noticed that in in this PR: https://github.com/moltar/typescript-runtime-type-benchmarks/pull/931
=> feat: improve benchmark preview svg

README.md, cases/index.ts, cases/rescript-struct.ts, package-lock.json, package.json, test/benchmarks.test.ts
Want to add my parsing library. Should be a new winner 😊
Also, I maintain a fork of the repo that contains some other parsing libraries for ReScript (without TS support). It's pretty tedious to do, so I thought maybe it's possible to move them to your repo and hide them behind a separate tab? What do you think? https://github.com/DZakh/rescript-runtime-type-benchmarks
=> Add rescript-struct to the benchmark

cases/sinclair-typebox.ts, package-lock.json, package.json
@moltar @hoeck Hi!
This PR updates TypeBox from version 0.24.41 to 0.25.21 (minor semver) which includes a number of optimizations  implemented since the 0.24.x release. In addition this PR applies a configuration update to align TypeBox type checking behaviors inline with TypeScript semantics for the following permissible cases. 
[TypeScript Link Here](https://www.typescriptlang.org/play?#code/PTAEEEBtIewd3AJ0QQwJ4HkBGArApgMYAuAzgLABQAZgK4B2xAljHaEXiUQIwAUAbikg08ALlAxchIgEpQAbwC+ldp14BtLgBpQAJm0BmbQBYAurJDiA1mKJoADnhhVQG7XtCHQp0AF4-oAHIJfGIAykoLKFg4ADkUGMpaBiJmVhUiHX5BYTE6GgBbLDxEWUVlDgyeOJjzMBhrNntHZ2rffwC8wuKAoA)
```typescript
// AllowArrayObjects
function test1(value: object) {}
test1([1, 2, 3, 4]) // ok: typeof [1, 2, 3, 4] === 'object'
// AllowNaN
function test2(value: number) {} …
```
=> chore(deps) typebox 0.24.41 > 0.25.21 | ts semantics

benchmarks/helpers/graph.ts, docs/results/preview.svg
fixes #1082
Sorting each individual preview bar chart by number of ops is not possible with this approach any more. That did only work due to hidden implementation behavior of vega-lite version 4.
=> fix: preview svg in vega lite v5

package-lock.json, package.json
Especially, `ts-runtime-checks` had a great change that performing exact object type validation.
- Previous: `typeof obj === "object"`
- Current: `typeof object === "object" && obj !== null`
By the way, the new version of `ts-runtime-checks` requires the latest TypeScript v5 version. And its based compiler `ttypescript` had been deprecated since `typescript@5` version, and `ts-patch` is continuing the project. Therefore, upgraded to `typescript@5`, and adopted `ts-patch`.
The other updates `typia` and `typebox`, it doesn't have special change on performance, but did because I know \o/.
=> build: upgrades `ts-runtime-checks` and `typescript` versions

README.md, cases/valibot.ts, package-lock.json, package.json
We might want to wait for https://github.com/fabian-hiller/valibot/pull/46 to be resolved since I expect that could improve the performance a lot
I ran `npm run start run valibot`:
Against `valibot@0.8.0`:
```
Removing previous results
Executing "valibot"
Loading "valibot"
Running "parseSafe" suite...
Progress: 100%
valibot:
303 700 ops/s, ±2.28%   | fastest
Finished 1 case!
Running "parseStrict" suite...
Progress: 100%
valibot:
338 906 ops/s, ±2.54%   | fastest
Finished 1 case!
```
Against https://github.com/fabian-hiller/valibot/pull/46:
```
Removing previous results
Executing "valibot"
Loading "valibot"
Running "parseSafe" suite...
Progress: 100%
valibot:
659 443 ops/s, ±1.68%   | fastest
Finished 1 case!
Running "parseStrict" suite...
Progress: 100%
valibot:
691 575 ops/s, ±1.99%   | …
```
=> feat: add valibot

cases/index.ts, test/benchmarks.test.ts
This is a follow up for https://github.com/moltar/typescript-runtime-type-benchmarks/pull/1112
=> Make valibot appear in benchmarks

cases/valibot.ts
cc: @fabian-hiller
`.parse()` on the Valibot schema was never intended to be used directly. 
I did not notice this while I did the change in https://github.com/moltar/typescript-runtime-type-benchmarks/pull/1112 since I was just relying on auto completion based on TypeScript types and `.parse` appeared. 
Note that the future version of Valibot [renamed it to `_parse`](https://github.com/fabian-hiller/valibot/blob/db2714403351b469eed8c8622613af5067db9514/library/src/schemas/object/object.ts#L93-L93) to avoid this confusion.
Anyway let's use the intended documented API. Otherwise, updating Valibot version in the future will break this test case. Note that this should not affect performance since internally it's just calling the `.parse` on the schema now.
=> chore: Use the correct API for Valibot (it should not affect perf)

cases/valibot.ts, package-lock.json, package.json
- this update has a significant performance increase associated with it
- also updating `valibot` imports to use tree shaking import pattern
```shell
Running "parseSafe" suite...
Progress: 100%
valibot:
2 029 764 ops/s, ±1.17%   | fastest
Finished 1 case!
Running "parseStrict" suite...
Progress: 100%
valibot:
1 982 199 ops/s, ±0.96%   | fastest
```
```shell
$ npm run start run valibot
Running "parseSafe" suite...
Progress: 100%
valibot:
129 373 ops/s, ±3.78%   | fastest
Finished 1 case!
Running "parseStrict" suite...
Progress: 100%
valibot:
145 368 ops/s, ±3.69%   | fastest
```
=> Update `valibot` to `0.13.0`

benchmarks/helpers/graph.ts, benchmarks/helpers/register.ts, cases/deepkit/src/index.ts, cases/index.ts, package-lock.json, package.json
Updating `gts` to latest, in hope to fix any issues from #1218.
=> chore: update `gts` to latest

cases/deepkit/index.ts, cases/mol_data.ts, cases/ts-runtime-checks/index.ts, cases/typia/index.ts, cases/typia/src/index.ts
I noticed that for some libraries, the operation is inlined instead of being called inside the benchmark callback.
Since there are many libraries that could be potentially inlined like this eg Zod, but they still used the benchmark callback, I've decided to walk through all the libraries that don't use it and fix them. I think it'll make the benchmark more honest.
=> Honest benchmark callback

package-lock.json, package.json
Just optimized `typia.misc.clone()` function a little bit, so that `safeParse()` benchmark of `typia` would be a little bit faster.
https://github.com/samchon/typia/pull/1197
=> Bump up `typia` version.

docs/app.tsx, docs/dist/app.js, tsconfig.docs.json
- Fixes selecting default version for nodejs
- Set target to ES5 as with current typescript version, there is warning 
`Option 'target=ES3' has been removed. Please remove it from your configuration.`
=> Updated runtime version reference and target JS version

docs/app.tsx, docs/dist/app.js
I think it makes sense for a benchmark to have sorted by fastest enabled by default. At least this is what I always choose whenever I open the benchmark.
=> Fastest sort by default

.eslintignore, .gitignore, README.md, cases/index.ts, cases/ts-auto-guard/index.ts, cases/ts-auto-guard/src/index.ts, cases/ts-auto-guard/tsconfig.json, index.ts, package-lock.json, package.json, test/benchmarks.test.ts
Add ts-auto-guard
https://github.com/rhys-vdw/ts-auto-guard
Closes https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1310
=> Add ts-auto-guard

cases/rescript-schema.ts, package-lock.json, package.json
Excited to see the results. I think I should have reached the limits of the JIT approach with the update.
=> Update rescript-schema to V9

.github/workflows/download-packages-popularity.yml, .github/workflows/release.yml
Closes https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1479
=> Update GitHub Actions to use EndBug/add-and-commit

docs/app.tsx
When selecting both node and bun the bars order and color was wrong:
This happened because the artificial name used to maintain the order didn't distinguish between node and bun.
In this PR I add another number at the beginning to separate node and bun:
=> fix ordering issue when both node and bun are selected

.eslintignore, .eslintrc.json, benchmarks/assertLoose.ts, benchmarks/assertStrict.ts, benchmarks/helpers/types.ts, benchmarks/parseSafe.ts, benchmarks/parseStrict.ts, jest.config.js, package-lock.json, package.json, test/benchmarks.test.ts
The what:
Replace Jest with [Vitest](https://vitest.dev/).
The why:
- Familiar Jest interface.
- Zero config TypeScript and ESM support (fighting the Jest configuration to do trivial things is not fun).
- Much faster test execution.
=> feat: Replace jest with vitest

.github/PULL_REQUEST_TEMPLATE.md
Add pull request template for consistency
=> docs: add pull request template for consistency

README.md
Enhance README with detailed command and debugging sections
Closes https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1545
=> docs: enhance README with detailed command and debugging sections

cases/io-ts.ts
io-ts [provides a way](https://github.com/gcanti/io-ts/blob/master/index.md#exact-types) to do a _Safe Parsing_ test if you use the `exact` or `strict` function. This PR adds a test case for that.
I believe the existing tests already cover the new case.
=> feat: add parseSafe case for io-ts

index.ts
fixes #1611
Skip failing benchmarks to not block other benchmarks from running properly.
This is a quick fix to keep libraries in the list that do not support older node versions like stnl that only seems to work for node 23.
One potential downside / danger is that we have to look out for dependabot changes that update library versions that later fail to run. So this fix is only an intermediate solution. We should replace ts-node with something more modern in the near future.
Check that even though stnl errors, the benchmark for valita still runs fine with node 22: `nvm use node 22; npm run start stnl valita`.
=> fix: skip failing benchmarks

.github/workflows/pr.yml, .github/workflows/release.yml, docs/src/App.tsx
Updates the Bun version matrix in GitHub workflows to use 1.2.12, removing older versions for consistency and alignment. Also refines the available Bun versions in documentation code to reflect these changes.
CI
=> ci: update Bun versions in workflows

.github/workflows/pr.yml, .github/workflows/release.yml, docs/src/App.tsx
Removes support for Node.js versions 16.x to 19.x in both PR and release workflows. Adds support for Node.js 24.x to ensure alignment with the latest runtime environments. Updates NODE_VERSIONS constant to match supported versions.
CI
=> chore: update Node.js versions in CI workflows
